In [3]:
import numpy as np
print(np.version.version)

1.24.2


In [6]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
t=np.full((3,3),True)
t

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
mask=a%2!=0
a[mask]

array([1, 3, 5, 7, 9])

In [12]:
a[mask]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
a=np.arange(10)
b=a.copy()
mask=b%2!=0
b[mask]=-1
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [25]:
a=np.arange(10)
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
a=np.array([1,2,3])
b=np.repeat(a,3)
b=np.concatenate([b,np.tile(a,3)])
b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [62]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)


array([1, 2, 3, 4])

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [76]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
mask=np.logical_and(a>4,a<11)
a[mask]

array([ 6,  9, 10])

In [80]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y



pair_max=np.vectorize(maxx,otypes=[int])

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])